---
- hosts: ubuntu_direct
  become: yes
  tasks:
  - name: Install OpenVPN
    ansible.builtin.apt:
      name: openvpn
      update_cache: yes

  - name: Copy client config file
    copy:
      src: /etc/openvpn/client/u-agent/u-agent.conf
      dest: /etc/openvpn/u-agent.conf

  - name: Start OpenVPN
    ansible.builtin.service:
      name: openvpn@u-agent
      state: started
      enabled: true
