---
- hosts: ubuntu_all
  become: yes
  tasks:
  - name: Install network-manager
    apt:
      name: network-manager
      state: present
  
  - name: Copy netplan config
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
      - { src: /etc/ansible/common/bind/50-cloud-init.yaml, dest: /etc/netplan/50-cloud-init.yaml }
      - { src: /etc/ansible/common/bind/99-disable-network-config.cfg, dest: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg }

  - name: netplan apply
    command: netplan apply

  - name: Configure NetWork
    command: '{{item}}'
    loop:
      - nmcli con mod "netplan-eth0" ipv4.ignore-auto-dns yes
      - nmcli con mod "netplan-eth0" ipv4.dns "10.0.0.2"
      - nmcli con mod "netplan-eth0" ipv4.dns-search "sf-alek.ru"
      - nmcli connection up "netplan-eth0" 
